// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://coadhiipbnnqlmslpzeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvYWRoaWlwYm5ucWxtc2xwemV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyODczNDgsImV4cCI6MjA2NTg2MzM0OH0.P37hdEGhEbZ_AWU1IAdFihnw2yhWEkWfClidFVjDqI4";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
